/*
 * File: app/view/RestaurantPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TileView.view.RestaurantPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.restopanel',

    requires: [
        'TileView.view.RestaurantList'
    ],

    height: 400,
    width: 600,
    layout: {
        type: 'border'
    },
    title: 'Restaurants',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'restaurantlist',
                    margins: '5',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});