/*
 * File: app/view/RestaurantList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TileView.view.RestaurantList', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.restaurantlist',

    requires: [
        'TileView.view.override.RestaurantList',
        'Ext.ux.container.SwitchButtonSegment'
    ],

    store: 'Restaurants',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    id: 'name',
                    dataIndex: 'name',
                    text: 'Name',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    id: 'cuisine',
                    dataIndex: 'cuisine',
                    text: 'Cuisine',
                    flex: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'splitbutton',
                            menu: {
                                xtype: 'menu',
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        viewMode: 'default',
                                        iconCls: 'icon-default',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        viewMode: 'tileIcons',
                                        iconCls: 'icon-tile',
                                        text: 'Menu Item'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        viewMode: 'mediumIcons',
                                        iconCls: 'icon-medium',
                                        text: 'Menu Item'
                                    }
                                ]
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});