/*
 * File: app/controller/Restaurant.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TileView.controller.Restaurant', {
    extend: 'Ext.app.Controller',

    stores: [
        'Restaurants'
    ],
    views: [
        'RestaurantPanel',
        'RestaurantList'
    ],

    refs: [
        {
            ref: 'restaurantList',
            selector: 'restaurantlist'
        }
    ],

    onMenuitemClick: function(item, e, eOpts) {
        var grid = this.getRestaurantList();
        grid.features[0].setView(item.viewMode);
    },

    init: function(application) {
        this.control({
            "splitbutton menuitem": {
                click: this.onMenuitemClick
            }
        });
    }

});
